apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: docker-repo.sk-devops.com/demo-python-app:v8c1a429
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: regcred
